apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-demo-prod

namePrefix: mlops-demo-prod-

resources:
  - ../../base

patches:
  - path: patch-subject-namespace.yaml
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-monitoring-view
