apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../base

patches:
  - path: patch-application-repo-revision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
  # Uncomment patches to disable automatic sync
  # - path: patch-application-manual-sync.yaml
  #   target:
  #     group: argoproj.io
  #     version: v1alpha1
  #     kind: Application
