apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-app-of-apps.yaml
    target:
      group: argoproj.io
      kind: Application
      name: mlops-demo-tenant-app-of-apps
      version: v1alpha1
