apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-demo-datascience

namePrefix: mlops-demo-datascience-

resources:
  - ../../base
  - pipeline-obc-viewer-rbac.yaml

patches:
  - path: patch-subject-namespace.yaml
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-monitoring-view
