---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: obc-view
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaims"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-obc-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: obc-view
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: mlops-demo-pipelines
