apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mlops-demo-rbac-applicationset.yaml
  - mlops-demo-tenant-app-of-apps.yaml
  - mlops-demo-tenant-argocd.yaml
  - mlops-demo-tenant-projects.yaml
