apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-demo-tenant-projects
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: mlops-demo-tenant
  source:
    path: tenants/mlops-demo/components/charts/tenant-projects
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      selfHeal: true
