apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mlops-demo-tenant-rbac
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: mlops-demo-tenant-rbac-datascience
              path: tenants/mlops-demo/components/rbac/overlays/datascience
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: mlops-demo-tenant-rbac-dev
              path: tenants/mlops-demo/components/rbac/overlays/dev
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: mlops-demo-tenant-rbac-test
              path: tenants/mlops-demo/components/rbac/overlays/test
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: mlops-demo-tenant-rbac-prod
              path: tenants/mlops-demo/components/rbac/overlays/prod
  template:
    metadata:
      name: '{{values.name}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: mlops-demo-tenant
      source:
        path: '{{values.path}}'
        repoURL: patch-me-see-tenant-overlays
        targetRevision: patch-me-see-tenant-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
