argocd:
  fullnameOverride: argocd
  rbac:
    policy: |-
      g, system:cluster-admins, role:admin
      g, mlops-demo-admins, role:admin
      g, pipeline, role:admin
    scopes: "[accounts,groups]"
  projects:
    - name: mlops-demo-dev
      destinations:
        - server: https://kubernetes.default.svc
          namespace: mlops-demo-dev
    - name: mlops-demo-test
      destinations:
        - server: https://kubernetes.default.svc
          namespace: mlops-demo-test
    - name: mlops-demo-prod
      destinations:
        - server: https://kubernetes.default.svc
          namespace: mlops-demo-prod
    - name: mlops-demo-pipelines
      destinations:
        - server: https://kubernetes.default.svc
          namespace: mlops-demo-pipelines
    - name: mlops-demo-datascience
      destinations:
        - server: https://kubernetes.default.svc
          namespace: mlops-demo-datascience
  pipelineAccounts:
    - name: pipeline
      namespace: mlops-demo-pipelines

  resourceCustomizations:
    machinelearning.seldon.io/SeldonDeployment:
      health.lua: |
        health_status = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            numConditions = 0
            numTrue = 0
            numFalse = 0
            message = ""
            for _, condition in pairs(obj.status.conditions) do
              numConditions = numConditions + 1
              if condition.status == "False" then
                numFalse = numFalse + 1
                message = message .. " " .. condition.type .. ": " .. condition.reason .. ";"
              elseif condition.status == "True" then
                numTrue = numTrue + 1
              end
            end
            if numTrue == numConditions then
              health_status.status = "Healthy"
              health_status.message = "SeldonDeployment is healthy"
              return health_status
            else
              health_status.status = "Progressing"
              health_status.message = message
              return health_status
            end
          end
        end

        health_status.status = "Progressing"
        health_status.message = "Waiting for SeldonDeployment"
        return health_status

  # resourceExclusions:
  #   - apiGroups:
  #       - tekton.dev
  #     clusters:
  #       - '*'
  #     kinds:
  #       - TaskRun
